### ISSUE TITLE
How to deploy this project ?

### ISSUE THREAD

**Issue by huangxiaoshuo** [RavenLite/NeusoftCloudHospital#29]
Hi, what an amazing work !
Will the functionality of this project run normally after deploying it on local server ? 
Could you provide me the database creating scripts or Demo database version?
Thanks very much !

**Comment by RavenLite** [comment]
Hi xiaoshuo,
Sorry for the late reply.
You can get the database creating scripts [here](https://github.com/RavenLite/NeusoftCloudHospital/blob/master/docs/cloud_hospital_1905271838.sql)
We have some updates nowadays, you could pull the updates if you need.

**Comment by huangxiaoshuo** [comment]
Thanks a lot.
